- name: Base_gmond
  tags: base, gmond
  block:
    ## need separate task for installing repo files
    - yum: pkg={{item}} state=present
      with_items:
        - epel-release
    ## and now the rest
    - yum: pkg={{item}} state=present
      with_items:
        - ganglia-gmond
    - copy:
        dest: "/etc/ganglia/{{item}}"
        src: "{{item}}"
      with_items:
        - gmond.conf
    - service: name=gmond   state=started enabled=true
