## Complete toolset
## you may not want this on a production host
## (do not make intruder's life easier)
- name: Base_tools
  tags: base
  block:
  - yum: pkg={{item}} state=present
    with_items:
    - libsemanage-python ## for ansible to set SELinux
    - mc ## Sergio's favourite shell
    - net-tools ## ifconfig, netstat etc
    - nc ## netcat
    - telnet
    - htop
    - iotop
    - psmisc ## pstree etc
    - jq  ## json processor
    - strace
    ## network debug tools
    - nmap
    - tcpdump
