---
- hosts: all
  vars:
    service: [] #[elasticsearch,logstash,kibana]
  roles:
    - base
    - elkrepo
    - elastic
    - logstash
    - kibana
    - filebeat
  tasks:
    - import_tasks: tasks/elastalert.yml
