# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision "bootstrap", type: "shell" do |s|
    s.inline = "echo bootstrap hostname=$(hostname)"
  end

  config.vm.define "elk0" do |m|
    ip="10.0.3.20"
    m.vm.hostname="elk0"
    m.vm.network "private_network", ip: "#{ip}",
      virtualbox__intnet: "NatNetwork3"
    m.vm.network "forwarded_port", guest: 5601, host: 5601 ## Kibana
    m.vm.network "forwarded_port", guest: 9200, host: 9200 ## ElasticSearch
    m.vm.network "forwarded_port", guest: 9600, host: 9600 ## LogStash
    ## Host-specific resource settings
    m.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  ## VBguest plugin - do not install automatically
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    ##
    ## https://www.vagrantup.com/docs/virtualbox/configuration.html
    vb.linked_clone = true
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # fix timesync of VirtualBox VMs
    # https://www.virtualbox.org/manual/ch09.html#changetimesync
    # https://superuser.com/questions/463106/virtualbox-how-to-sync-host-and-guest-time
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-interval",       "10000"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-min-adjust",     "100"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore", "1"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-start",      "1"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold",  "10000" ] 
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible-elk0.yml"
    ansible.become = true
    ansible.become_user = "root"
    ansible.compatibility_mode = "2.0"
  end
end
