- name: Kibana
  tags: elk,kibana
  block:
  - yum: pkg={{item}} state=present
    with_items:
    #- java-1.8.0-openjdk
    - kibana
#  - copy:
#      dest: /etc/elasticsearch/elasticsearch.yml
#      src:  elasticsearch.yml
#      owner: root
#      group: root
#      backup: yes
  - service: name=kibana state=started
