- name: Base_NTP
  tags: base,ntp
  block:
  - yum: pkg={{item}} state=present
    with_items:
    - ntp
  - service: name=ntpd state=started enabled=true

#- name: Base_gmond
#  tags: base, gmond
#  block:
  #- yum: pkg=

- name: Base_tools
  tags: base
  block:
  - yum: pkg={{item}} state=present
    with_items:
    - mc
    - nmap
    - net-tools
    - nc
    - telnet
    - tcpdump

