- name: Base_NTP
  tags: base,ntp
  block:
  - yum: pkg={{item}} state=present
    with_items:
    - ntp
  ## VirtualBox VMs fall behind when using ntpd - disable
  - service: name=ntpd state=stopped enabled=false
  ## and use instead the Guest Addition
  - service: name=vboxadd-service state=started enabled=true
  ## this part should go in block/when depending on VM type / HW

#- name: Base_gmond
#  tags: base, gmond
#  block:
  #- yum: pkg=

- name: Base_tools
  tags: base
  block:
  - yum: pkg={{item}} state=present
    with_items:
    - mc
    - nmap
    - net-tools
    - nc
    - telnet
    - tcpdump
    - htop
    - iotop

