  ## ugly, dev tools on producion server
  ## we should probably use bundles instead
  ## https://pip.pypa.io/en/stable/user_guide/#installation-bundles

  - yum: pkg={{item}} state=present
    with_items:
    #- java-1.8.0-openjdk
    - python2-pip
    - gcc ## 
    - python-devel
  - name: pip dontcomplain
    copy:
      dest: /etc/pip.conf
      content: "## AnsibleManaged\n[global]\ndisable_pip_version_check = 1\n"
  - pip: 
      name: "{{item}}"
    with_items:
    - "setuptools>=11.3" ## system installed is 0.9.8
    - "elasticsearch"#<6.0.0" ## while running ELKv5
    - "elastalert"

  - group:
      name: elastalert
      system: true

  - user:
      name: elastalert
      comment: "ElastAlert service user"
      system: true
      shell: /bin/bash
      group: elastalert
      createhome: yes

  - name: elastalert systemd 
    copy:
      dest: /etc/systemd/system/elastalert.service
      src: elastalert.service
  ## try to use rsync --delete to cleanup unwanted local files - sergio, Feb 2018
  - name: elastalert configuration
    synchronize:
      dest: /etc/elastalert/
      src: elastalert/
      mode: push # just to be clear
      delete: yes
      archive: yes 
      owner: no # ansible crap - avoid wrong user/group
      group: no # ansible crap - avoid wrong user/group
      rsync_opts:
        - "--exclude=.DS_Store" # mac crap
    ##notify etc
  ## make sure rsync or root didn't mess up ownership
  - name: elastalert configuration owner
    file:
      dest: /etc/elastalert/
      state: directory
      owner: root
      group: root
      mode: a=rX,u+w  # 644 doesn't work for directories
      recurse: yes
    ##notify etc

  ## use this instead of service, make sure config is reloaded
  - systemd: name=elastalert state=started enabled=true daemon-reload=true

  ## dev installation for testing
  - yum: pkg=git state=present
  #- git:
  #    dest: /root/elastalert
  #    src: https://github.com/Yelp/elastalert.git
