---
- hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
  roles:
    - base
    - elkrepo
    #- elastic
    #- logstash
    #- kibana
    - filebeat

- hosts: elk1
  roles:
    #- elkrepo
    - elastic
    - logstash
    - kibana

- hosts: elk2
  roles:
    #- elkrepo
    - elastic
    #- logstash
    #- kibana
