- name: LogStash
  tags: elk,logstash
  block:
  - yum: pkg={{item}} state=present
    with_items:
    #- java-1.8.0-openjdk
    - logstash
  - copy:
      dest: /etc/logstash/conf.d/logstash.conf
      src:  logstash.conf
      owner: root
      group: root
      backup: yes
  - copy:
      dest: /etc/logstash/logstash.yml
      src:  logstash@{{ansible_hostname}}.yml
      owner: root
      group: root
      backup: yes
  - copy:
      dest: /etc/logstash/elasticsearch-template.conf
      src:  elasticsearch-template.conf
      owner: root
      group: root
      backup: yes
  ## do not set to autostart, for flexible testing
  - service: name=logstash state=started

## enforce permissions
## chown -R logstash.logstash /var/lib/logstash/
